# Generated by Django 3.2.5 on 2021-08-23 19:28

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whiskey', '0002_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='whiskey.type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='country',
            field=django_countries.fields.CountryField(max_length=6),
        ),
    ]
