# Generated by Django 3.2.5 on 2021-08-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiskey', '0004_auto_20210823_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('released', models.IntegerField()),
                ('age_statement', models.CharField(max_length=3)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='brand', to='whiskey.brand')),
            ],
        ),
    ]
