# Generated by Django 3.2.5 on 2021-08-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskey', '0005_whiskey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whiskey',
            name='released',
        ),
        migrations.AddField(
            model_name='whiskey',
            name='chill_filtered',
            field=models.CharField(choices=[(0, 'Unknown'), (1, 'Chill-filtered'), (2, 'Non-chill-filtered')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='whiskey',
            name='colour',
            field=models.CharField(choices=[(0, 'Unknown'), (1, 'Coloured'), (2, 'Natural')], default=0, max_length=1),
        ),
    ]
