# Generated by Django 3.2.5 on 2021-08-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskey', '0006_auto_20210824_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskey',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whiskey',
            name='image',
            field=models.ImageField(default='1', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='chill_filtered',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Chill-filtered'), ('2', 'Non-chill-filtered')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='colour',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Coloured'), ('2', 'Natural')], default='0', max_length=1),
        ),
    ]
