# Generated by Django 3.2.5 on 2021-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskey', '0007_auto_20210830_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whiskey',
            name='image',
        ),
        migrations.AddField(
            model_name='whiskey',
            name='proof',
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
    ]
