# Generated by Django 3.2.5 on 2021-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskey', '0008_auto_20210831_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskey',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
