# Generated by Django 3.2.5 on 2021-08-31 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiskey', '0009_whiskey_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='type',
        ),
        migrations.AddField(
            model_name='whiskey',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='type', to='whiskey.type'),
            preserve_default=False,
        ),
    ]
